### ISSUE TITLE
Arrival platform numbers are not available

### ISSUE THREAD

**Issue by hb9tst** [OpendataCH/Transport#172]
When looking up a journey, arrival platform numbers are never available on the beta API, whereas departure platforms are. On the "normal" API, both are available all the time. This information is not critical, but is sometimes very useful (e.g. to estimate if a connection is doable with a lot of luggage to transport...).

For example, http://transport.opendata.ch/v1/connections?from=Pully&to=Lutry&time=10:00 returns (cutting out of course all the irrelevant fields):

```
{
  "connections": [
    {
      "sections": [
        {
          "departure": {
            "platform": "2",
          },
          "arrival": {
            "platform": "2",
          },
```

Whereas the same query on the beta version gives:

```
{
  "connections": [
    {
      "sections": [
        {
          "departure": {
            "platform": "2",
          },
          "arrival": {
            "platform": null,
          },
```

**Comment by hb9tst** [comment]
Looks like the information is not available on timetable.search.ch either...

**Comment by helbling** [comment]
I added the arrival tracks to the timetable.search.ch API

**Comment by hb9tst** [comment]
Looks like the problem is solved then, the information appears also on transport.opendata.ch... thanks!

**Comment by simon-isler** [comment]
@fabian any update on this? The arrival platforms still don't seem to work properly.

The following request gives me the correct departure platforms, but incorrect **arrival** platforms.
`https://transport.opendata.ch/v1/connections?to=Zurich&from=Schaffhausen`

<details>
<summary>Response</summary>

```json
{
    "connections": [
        {
            "from": {
                "platform": "5"
            },
            "to": {
                "platform": "5"
            }
        },
        {
            "from": {
                "platform": "3"
            },
            "to": {
                "platform": "3"
            }
        },
        {
            "from": {
                "platform": "5"
            },
            "to": {
                "platform": "5"
            }
        },
        {
            "from": {
                "platform": "3"
            },
            "to": {
                "platform": "3"
            }
        }
    ]
}
```

</details>
